#Builds on every commit to main.
name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore Source/HtmlRendererCore.sln

    - name: Build
      run: dotnet build --no-restore Source/HtmlRendererCore.sln -p:Version=${{ format('0.9.{0}', github.run_number) }}